FROM node:22-alpine AS builder

# Install git + optional bash
RUN apk add --no-cache git bash

WORKDIR /app

# Copy package files and install dependencies
COPY package.json ./
COPY tsconfig.json ./
COPY . .
RUN npm install

# Build TypeScript
ARG SENTRY_AUTH_TOKEN
RUN npm run build
# RUN npx sentry-cli login --auth-token $SENTRY_AUTH_TOKEN
# RUN npx sentry-cli sourcemaps inject --org dled --project backend-users ./build && npx sentry-cli sourcemaps upload --org dled --project backend-users ./build

# ---- Production image ----
FROM node:22-alpine

WORKDIR /app

# Install bash for runtime if needed
RUN apk add --no-cache git bash

# Copy only production dependencies and compiled code
COPY package.json ./
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/build ./build
RUN npm install

# Set environment and port
# ENV NODE_ENV=development
# ENV MODULE=all
# ENV SENTRY_PROJECT=vibe-backend
# ENV SENTRY_ORG=dled
ENV APP_PORT=4001
EXPOSE 4001

# Run the compiled JS
CMD ["node", "build/index.js"]
